#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
runApplication decomposePar
runApplication mpirun --oversubscribe -np 48 denseParticleFoam -parallel
runApplication reconstructPar
runApplication foamToVTK
runApplication particleTracks

#------------------------------------------------------------------------------
